name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Docker Compose
        run:
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run containers
        run:
          docker-compose up --build -d

      - name: Install dependencies
        run:
          sudo apt-get install python3-venv &
          python3 -m venv venv &
          source venv/bin/activate &
          pip install --upgrade pip &
          pip install -r requirements.txt

      - name: Run tests
        run:
          sudo apt-get install docker-compose &&
          sudo service postgresql stop
          sudo docker-compose up